# Generated by Django 4.2.1 on 2023-05-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=50)),
                ('ruc_cliente', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='detalle_factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.CharField(max_length=10)),
                ('id_producto', models.CharField(max_length=10)),
                ('cantidad_producto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.CharField(max_length=10)),
                ('fecha_emision', models.CharField(max_length=50)),
                ('id_cliente', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad_stock', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
    ]
